### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by CheaterHu** [develon2015/Youtube-dl-REST#9]
rs = child_process.execSync(`youtube-dl ${config.cookie !== undefined ? `--cookies ${config.cookie}` : ''} -F '${msg.url}' 2> /dev/null`).toString().split('\n'); 
执行到这一句就卡住了，页面表现为：一直是正在解析。
网络是可用的，能访问墙外网络

**Comment by develon2015** [comment]
修改config.json配置文件，删除掉cookie字段就可以了，cookie是被油管拉黑时使用的。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："CheaterHu "<notifications@github.com&gt;;
发送时间：2020年7月3日(星期五) 晚上9:45
收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[develon2015/Youtube-dl-REST] 下载失败 (#9)
-----------------------------------

 

 
rs = child_process.execSync(youtube-dl ${config.cookie !== undefined ? --cookies ${config.cookie} : ''} -F '${msg.url}' 2&gt; /dev/null).toString().split('\n');
 执行到这一句就卡住了，页面表现为：一直是正在解析。
 网络是可用的，能访问墙外网络

**Comment by CheaterHu** [comment]
> 修改config.json配置文件，删除掉cookie字段就可以了，cookie是被油管拉黑时使用的。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："CheaterHu "<notifications@github.com&gt;; 发送时间：2020年7月3日(星期五) 晚上9:45 收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[develon2015/Youtube-dl-REST] 下载失败 (#9) ----------------------------------- rs = child_process.execSync(youtube-dl ${config.cookie !== undefined ? --cookies ${config.cookie} : ''} -F '${msg.url}' 2&gt; /dev/null).toString().split('\n'); 执行到这一句就卡住了，页面表现为：一直是正在解析。 网络是可用的，能访问墙外网络 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 修改config.json配置文件，删除掉cookie字段就可以了，cookie是被油管拉黑时使用的。
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："CheaterHu "<notifications@github.com&gt;; 发送时间：2020年7月3日(星期五) 晚上9:45 收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[develon2015/Youtube-dl-REST] 下载失败 (#9) ----------------------------------- rs = child_process.execSync(youtube-dl ${config.cookie !== undefined ? --cookies ${config.cookie} : ''} -F '${msg.url}' 2&gt; /dev/null).toString().split('\n'); 执行到这一句就卡住了，页面表现为：一直是正在解析。 网络是可用的，能访问墙外网络 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

删除了还是不行呢。rs是空的，解析失败。

**Comment by develon2015** [comment]
youtube-dl和ffmpeg这两个命令下载了吗？

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："CheaterHu "<notifications@github.com&gt;;
发送时间：2020年7月3日(星期五) 晚上11:03
收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;;
抄送："Develon "<201621092106@scuec.edu.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [develon2015/Youtube-dl-REST] 下载失败 (#9)
-----------------------------------

 

  
修改config.json配置文件，删除掉cookie字段就可以了，cookie是被油管拉黑时使用的。
 …
 ---------- 该邮件从移动设备发送
 --------------原始邮件-------------- 发件人："CheaterHu "<notifications@github.com&gt;; 发送时间：2020年7月3日(星期五) 晚上9:45 收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[develon2015/Youtube-dl-REST] 下载失败 (#9) ----------------------------------- rs = child_process.execSync(youtube-dl ${config.cookie !== undefined ? --cookies ${config.cookie} : ''} -F '${msg.url}' 2&gt; /dev/null).toString().split('\n'); 执行到这一句就卡住了，页面表现为：一直是正在解析。 网络是可用的，能访问墙外网络 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
修改config.json配置文件，删除掉cookie字段就可以了，cookie是被油管拉黑时使用的。
 …
 ---------- 该邮件从移动设备发送
 --------------原始邮件-------------- 发件人："CheaterHu "<notifications@github.com&gt;; 发送时间：2020年7月3日(星期五) 晚上9:45 收件人："develon2015/Youtube-dl-REST" <Youtube-dl-REST@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[develon2015/Youtube-dl-REST] 下载失败 (#9) ----------------------------------- rs = child_process.execSync(youtube-dl ${config.cookie !== undefined ? --cookies ${config.cookie} : ''} -F '${msg.url}' 2&gt; /dev/null).toString().split('\n'); 执行到这一句就卡住了，页面表现为：一直是正在解析。 网络是可用的，能访问墙外网络 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
删除了还是不行呢。rs是空的，解析失败。

**Comment by CheaterHu** [comment]
肯定是安装了的啊，删除cookie也不行，还是一直正在解析，请稍后

**Comment by develon2015** [comment]
可能是由于ajax请求的参数中含有油管URL而被某防火墙重置连接, 建议使用CloudFlare提供的HTTPS服务解决该问题

**Comment by CheaterHu** [comment]
为什么用的打开下载开始很快，过一会就慢的不行，基本不动

**Comment by CheaterHu** [comment]
为什么用的打开下载开始很快，过一会就慢的不行，基本不动
